# this file can be named anything but must be YML type and be located in models/
# when creating tests for seeds, macros, snapshots (i.e. not models)... you'd save this in their respective directories
# there can be multiple test files in a single directory

version: 2 # always version 2

models:
  - name: customers
    description: One record per customer with fields from orders
    columns:
      - name: customer_id
        description: Primary key of the model
        tests:
          - unique
          - not_null

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
